"""
This module is the bridge between the Django web layer and the AI engine.
It handles three responsibilities:
 
    1. Rendering the visit form (new_visit)
    2. Running the full AI pipeline and persisting results (run_analysis)
    3. Saving doctor annotations post-analysis (save_doctor_notes)
 
Design decisions worth noting:
 
    - The AI engine (engine.py) is deliberately kept stateless — it knows
      nothing about Django models, users, or the database. This module is
      responsible for feeding it patient history as plain text, and for
      saving its output back to the database.
 
    - The Visit record is created BEFORE the AI call so it gets a primary
      key. If the AI call fails, the visit is deleted (rolled back manually).
      This ensures no orphaned Visit records accumulate on engine errors.
 
    - Patient history is injected as enriched_symptoms text, not as a
      separate parameter. This keeps the engine interface simple — one
      symptoms string in, one structured dict out — while still giving
      Gemma 4 the full clinical context it needs for returning patients.
 
    - Sources are always extracted from ChromaDB chunk metadata in the
      engine, never generated by the LLM. This module does not need to
      handle source validation — it trusts the engine's output on that.
"""

import sys
import os
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.contrib import messages

from patients.models import Patient
from .models import Visit, Diagnosis

# Add ai/ directory to sys.path so we can import engine.py directly.
# The engine lives outside the Django app structure intentionally —
# it can be tested and run independently of Django.
AI_DIR = settings.BASE_DIR / "ai"
if str(AI_DIR) not in sys.path:
    sys.path.insert(0, str(AI_DIR))


def _patient_or_403(user, pk):
    """
    Return the patient if the user has access, or raise 404.
 
    Access control is enforced here via _patient_queryset:
        - Facility admins see all patients
        - Clinical officers see only their own registered patients
 
    This is called at the start of every view to ensure a doctor
    cannot access or analyse a patient registered by another doctor.
    """
    from patients.views import _patient_queryset
    return get_object_or_404(_patient_queryset(user), pk=pk)


def _build_history_context(patient, current_visit_pk=None):
    """
    Build a plain-text summary of the patient's clinical history
    for injection into the AI engine prompt.
 
    Why plain text instead of structured data?
    The engine accepts a single symptoms string. Injecting history
    as formatted text means the reasoning pass can reference it
    naturally — "as noted in the previous visit..." — without
    requiring the engine to understand Django model relationships.
 
    What gets included:
        - Known conditions (e.g. hypertension, diabetes, HIV status)
        - Allergies (critical for treatment safety)
        - Current medications (drug interaction context)
        - Up to 5 previous visits with symptoms, AI suggestion,
          confirmed diagnosis, and triage level
 
    current_visit_pk is excluded to prevent the engine from seeing
    the visit it is currently analysing (which would be empty anyway,
    but exclusion keeps the logic clean).
 
    Returns an empty string for new patients — the engine handles
    this gracefully with no history context.
    """
    visits = patient.visits.exclude(pk=current_visit_pk).prefetch_related("diagnoses")[:5]
    if not visits:
        return ""

    lines = [f"PATIENT HISTORY for {patient.get_full_name()} ({patient.patient_id}):"]

    if patient.known_conditions:
        lines.append(f"Known conditions: {patient.known_conditions}")
    if patient.allergies:
        lines.append(f"Allergies: {patient.allergies}")
    if patient.current_medications:
        lines.append(f"Current medications: {patient.current_medications}")

    lines.append("\nPrevious visits:")
    for v in visits:
        lines.append(f"  - {v.created_at:%d %b %Y}: {v.symptoms[:100]}")
        for dx in v.diagnoses.all()[:1]:
            if dx.final_diagnosis:
                lines.append(f"    Final diagnosis: {dx.final_diagnosis}")
            elif dx.diagnoses_json:
                top = dx.diagnoses_json[0].get("name", "")
                lines.append(f"    AI suggestion: {top}")
            lines.append(f"    Triage: {dx.triage_level}")

    return "\n".join(lines)


@login_required
def new_visit(request, patient_pk):
    """
    Render the new visit / symptom analysis form.
 
    Pre-fills the age group selector from the patient's date of birth
    or recorded age. For female patients of reproductive age (15–49),
    the "Pregnant woman" option is surfaced — the clinical officer
    can override the pre-filled selection.
 
    No AI call happens here. This view only renders the form.
    The actual analysis is triggered by a POST to run_analysis.
    """
    patient = _patient_or_403(request.user, patient_pk)
    history = _build_history_context(patient)

    # Pre-fill age group from patient record
    age_group = patient.get_age_group()
    if patient.sex == "F":
        # Offer pregnant option for women of reproductive age
        age = None
        if patient.date_of_birth:
            from django.utils import timezone
            age = (timezone.now().date() - patient.date_of_birth).days // 365
        elif patient.age_years:
            age = patient.age_years
        if age and 15 <= age <= 49:
            age_group = age_group  # doctor can override in form

    return render(request, "diagnoses/new_visit.html", {
        "patient":   patient,
        "age_group": age_group,
        "history":   history,
        "settings_choices": Visit.SETTING_CHOICES,
        "duration_choices": [
            "Less than 24 hours", "1–3 days", "4–7 days", "More than 1 week"
        ],
        "age_choices": [
            "Adult (18+)", "Child (5–17)", "Under 5", "Elderly (60+)", "Pregnant woman"
        ],
    })


@login_required
@require_POST
def run_analysis(request, patient_pk):
    """
    AJAX endpoint — runs the full 4-step Clinical Intelligence Pipeline
    and persists the result to the database.
 
    Request: POST with form fields:
        symptoms  — plain text symptom description (required)
        age_group — one of 5 age group strings
        duration  — symptom duration string
        setting   — facility setting string
        notes     — optional additional clinical observations
 
    Response: JSON containing the full structured assessment plus
        visit_id and diagnosis_id for the frontend annotation form.
 
    Pipeline flow:
        1. Validate input and resolve patient access
        2. Create Visit record (gets a PK before AI call)
        3. Build enriched_symptoms = symptoms + patient history text
        4. Call engine.analyse_symptoms() — the full RAG pipeline
        5. On engine failure: delete the Visit and return error
        6. On success: create Diagnosis record with full JSON output
        7. Return the result JSON with visit_id and diagnosis_id appended
 
    Why save the Visit before the AI call?
        The Visit needs a PK so we can exclude it from the history
        context in _build_history_context. We delete it on failure
        to keep the database clean.
 
    Why inject history as enriched_symptoms text?
        The engine's interface is intentionally simple: one symptoms
        string in, one structured dict out. Injecting history as text
        keeps the engine stateless and independently testable.
 
    Why store the full AI output as JSON fields?
        The Diagnosis model stores diagnoses_json, tests_json,
        treatments_json etc. as separate JSONFields rather than one
        blob. This allows future queries like "all URGENT diagnoses
        this month" without parsing JSON in application code.
    """
    patient = _patient_or_403(request.user, patient_pk)

    symptoms  = request.POST.get("symptoms", "").strip()
    age_group = request.POST.get("age_group", patient.get_age_group())
    duration  = request.POST.get("duration",  "1–3 days")
    setting   = request.POST.get("setting",   "outpatient")
    notes     = request.POST.get("notes",     "")

    if not symptoms:
        return JsonResponse({"error": "Symptoms are required."}, status=400)

    # Normalise setting string to its database key.
    # The form sends the display label ("Outpatient") but the model
    # stores the short key ("outpatient").
    setting_key = next(
        (k for k, v in Visit.SETTING_CHOICES if v.lower() == setting.lower()),
        "outpatient"
    )

    # Create the Visit record before calling the engine.
    # If the engine fails, this record is deleted in the except block.
    visit = Visit.objects.create(
        patient=patient,
        doctor=request.user,
        symptoms=symptoms,
        duration=duration,
        setting=setting_key,
        notes=notes,
    )

    # Run AI engine
    try:
        # Import here rather than at module level — the engine is not
        # a Django app and its dependencies (ollama, chromadb) should
        # only be loaded when an analysis is actually requested.
        from engine import analyse_symptoms

        # Build enriched context: symptoms + patient history.
        # The history is injected as plain text appended to the symptoms
        # string. Gemma 4 receives it as part of the user message in the
        # reasoning pass — "previous visits" context feeds naturally into
        # its deliberation without requiring any engine changes.
        history_ctx = _build_history_context(patient, current_visit_pk=visit.pk)
        enriched_symptoms = symptoms
        if history_ctx:
            enriched_symptoms = f"{symptoms}\n\n{history_ctx}"

        result = analyse_symptoms(
            symptoms=enriched_symptoms,
            age_group=age_group,
            duration=duration,
            setting=setting,
        )
    except Exception as e:
        # Roll back the Visit if the engine fails entirely.
        # Partial failures (bad JSON, missing keys) are handled inside
        # the engine's validation layer — only exceptions bubble up here.
        visit.delete()  # rollback visit if AI fails
        return JsonResponse({"error": f"AI engine error: {str(e)}"}, status=500)

    # Persist the structured result to the Diagnosis model.
    # Each component of the AI output is stored in its own JSONField
    # so individual lists (diagnoses, tests, treatments) can be queried
    # independently in reports without parsing a single large blob.
    triage = result.get("triage", {})
    meta   = result.get("_meta", {})

    dx = Diagnosis.objects.create(
        visit           = visit,
        triage_level    = triage.get("level",  "MODERATE"),
        triage_label    = triage.get("label",  ""),
        triage_reason   = triage.get("reason", ""),
        diagnoses_json  = result.get("diagnoses",  []),
        tests_json      = result.get("tests",      []),
        treatments_json = result.get("treatments", []),
        red_flags_json  = result.get("red_flags",  []),
        sources_json    = result.get("sources",    []),
        reasoning       = result.get("reasoning",  ""),
        disclaimer      = result.get("disclaimer", ""),
        llm_model       = meta.get("model",            ""),
        latency_s       = meta.get("latency_s",        None),
        chunks_used     = meta.get("chunks_retrieved", None),
    )

    # Append database PKs to the result so the frontend can
    # render the doctor annotation form pointing to the right records.
    result["visit_id"] = visit.pk
    result["diagnosis_id"] = dx.pk
    return JsonResponse(result)


@login_required
def visit_detail(request, pk):
    """
    Render a saved visit and its diagnosis results.
 
    Uses select_related and prefetch_related to avoid N+1 queries
    when rendering the patient, doctor, and diagnosis data together.
    """
    visit = get_object_or_404(
        Visit.objects.select_related("patient", "doctor").prefetch_related("diagnoses"),
        pk=pk,
        doctor=request.user if not request.user.is_facility_admin() else visit.doctor,
    )
    return render(request, "diagnoses/visit_detail.html", {"visit": visit})


@login_required
@require_POST
def save_doctor_notes(request, dx_pk):
    """
    Save the clinical officer's annotations on an AI-generated diagnosis.
 
    Two fields are saved:
        final_diagnosis — the doctor's confirmed diagnosis after examination
                          and any investigation results. This is the ground
                          truth that overrides the AI suggestion in future
                          history context for this patient.
        doctor_notes    — free-text clinical notes, follow-up plan, or
                          observations that the AI did not capture.
 
    Why is confirmed diagnosis important?
        When this patient returns, _build_history_context prefers
        final_diagnosis over the AI suggestion. A doctor confirming
        "Malaria (RDT positive)" rather than leaving the AI's
        "Possible Malaria (75%)" means future analyses get ground
        truth in their history context — improving accuracy over time.
    """
    dx = get_object_or_404(Diagnosis, pk=dx_pk, visit__doctor=request.user)
    dx.doctor_notes    = request.POST.get("doctor_notes", "")
    dx.final_diagnosis = request.POST.get("final_diagnosis", "")
    dx.save()
    messages.success(request, "Notes saved.")
    return redirect("patients:detail", pk=dx.visit.patient.pk)