# Generated by Django 6.0.4 on 2026-05-04 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting', models.CharField(choices=[('outpatient', 'Outpatient'), ('emergency', 'Emergency'), ('inpatient', 'Inpatient ward'), ('community', 'Community / Village'), ('hcii', 'Health Centre II/III')], default='outpatient', max_length=20)),
                ('symptoms', models.TextField()),
                ('duration', models.CharField(default='1–3 days', max_length=40)),
                ('notes', models.TextField(blank=True, help_text="Doctor's additional notes")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triage_level', models.CharField(choices=[('URGENT', 'Urgent'), ('MODERATE', 'Moderate'), ('LOW', 'Low')], default='MODERATE', max_length=10)),
                ('triage_label', models.CharField(blank=True, max_length=120)),
                ('triage_reason', models.TextField(blank=True)),
                ('diagnoses_json', models.JSONField(default=list)),
                ('tests_json', models.JSONField(default=list)),
                ('treatments_json', models.JSONField(default=list)),
                ('red_flags_json', models.JSONField(default=list)),
                ('sources_json', models.JSONField(default=list)),
                ('reasoning', models.TextField(blank=True)),
                ('disclaimer', models.TextField(blank=True)),
                ('llm_model', models.CharField(blank=True, max_length=40)),
                ('latency_s', models.FloatField(blank=True, null=True)),
                ('chunks_used', models.IntegerField(blank=True, null=True)),
                ('doctor_notes', models.TextField(blank=True, help_text="Doctor's annotations on this result")),
                ('final_diagnosis', models.CharField(blank=True, help_text="Doctor's confirmed final diagnosis", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='diagnoses.visit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
