# Generated by Django 6.0.4 on 2026-05-04 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other / Unknown')], default='O', max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age_years', models.PositiveIntegerField(blank=True, help_text='Enter if date of birth unknown', null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('next_of_kin', models.CharField(blank=True, max_length=100)),
                ('nok_phone', models.CharField(blank=True, max_length=20, verbose_name='Next of kin phone')),
                ('known_conditions', models.TextField(blank=True, help_text='e.g. Hypertension, Diabetes, HIV positive')),
                ('allergies', models.TextField(blank=True)),
                ('current_medications', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
